export const tweets = {
    "1": "Switching to a VOIP phone system can reduce your company's communication costs by up to 50%",
    "2": "On-premise systems offer greater control (and cost savings) for businesses with specific compliance and customization needs",
    "3": "Companies using @Google Workspace report a 20% increase in employee collaboration efficiency",
    "4": "90% of common IT issues can be resolved without a technician visiting your site",
    "5": "Around 70% of businesses experience at least one networking failure each year, highlighting the need for reliable IT support",
    "6": "A well-maintained computer network can reduce operational hiccups by 50%",
    "7": "Branding isn't just logos; it's your business personality, and it affects customer trust and recognition",
    "8": "Investing in UX Design can increase conversion rates by up to 400%",
    "9": "Companies utilizing print marketing alongside digital campaigns see a 25% higher consumer engagement rate",
    "10": "Interactive experiences can boost consumer engagement by 30%",
    "11": "Businesses with kiosks and #OOH advertising see up to a 60% increase in in-store traffic",
    "12": "Websites adhering to Section 508 and #WCAG are more accessible to over 60 million Americans with disabilities",
    "13": "AMP pages load 4x faster and use 10x less data compared to non-AMP pages",
    "14": "Custom applications for your business can increase work process efficiency by an average of 30%",
    "15": "Websites with responsive design increases mobile traffic by 50% on average",
    "18": "Regular cost analysis can save businesses up to 30% in cloud expenditure",
    "19": "Monitoring and maintenance of technical systems is crucial; nearly 40% of downtime is due to failed updates or changes",
    "20": "Implementing #SEO strategies can improve web traffic by up to 300%",
    "21": "Businesses using AdWords see an average return on investment of 8:1",
    "22": "Email marketing provides the highest ROI among all digital marketing channels, averaging $42 for every $1 spent",
    "23": "Web banners are highly effective for brand recall, with an average 16% increase in brand searches",
    "24": "High-converting Landing pages can increase ROI by up to 50%",
    "26": "Software engineering isn't just coding; it's about solving real-world problems through innovation",
    "27": "Over 60% of web traffic comes from mobile devices; the value of responsive web design is undeniable",
    "28": "Every dollar spent on UI/UX design can yield a return of up to $100",
    "29": "Nearly 30% of businesses are overspending on redundant cloud resources",
    "30": "Server optimization isn’t a one-time task; it’s an ongoing process, and can reduce operating costs by up to 40%"
}
