export const tweets = {
    "1": "linux powers many of the world's servers, known for its stability and security. #linux",
    "2": "macos integrates hardware and software seamlessly for a smooth user experience. #macos",
    "3": "windows continues to dominate the pc market with a variety of options for all users. #windows",
    "4": "networking technologies enable global connections, powering modern communication. #networking",
    "5": "interactive productions transform user experiences through engaging content and design. #interactive",
    "6": "programming is the foundation of all modern tech, enabling innovation. #programming",
    "7": "digital marketing bridges businesses with customers in a connected world. #marketing",
    "8": "open-source software powers innovation and community-driven development. #opensource",
    "9": "cloud computing provides scalable and flexible solutions for businesses of all sizes. #cloud",
    "10": "virtual reality is shaping the future of entertainment and education. #vr",
    "11": "internet of things devices are revolutionizing how we interact with everyday objects. #iot",
    "12": "machine learning algorithms drive personalization and automation in various industries. #ml",
    "13": "blockchain technology ensures transparency and security in various applications. #blockchain",
    "14": "cybersecurity measures are vital in protecting sensitive information and assets. #security",
    "15": "devops practices improve collaboration and efficiency in software development. #devops",
    "16": "artificial intelligence is automating tasks and enhancing decision-making processes. #ai",
    "17": "mobile applications enable access to services and information on the go. #mobile",
    "18": "big data analytics offer insights and trends from complex data sets. #bigdata",
    "19": "quantum computing is paving the way for new levels of computational power. #quantum",
    "20": "game development thrives on creativity and technology, connecting players worldwide. #gamedev",
    "21": "5g networks are enabling faster and more reliable mobile connectivity. #5g",
    "22": "responsive web design ensures seamless browsing across various devices. #webdesign",
    "23": "data privacy regulations safeguard personal information in the digital age. #privacy",
    "24": "wearable technology integrates computing into daily lives through gadgets. #wearables",
    "25": "tech startups are driving innovation and entrepreneurship in the global economy. #startups",
    "26": "remote work technology allows flexibility and collaboration from anywhere. #remotework",
    "27": "edge computing processes data closer to its source for faster responses. #edgecomputing",
    "28": "video streaming services are transforming how we consume entertainment. #streaming",
    "29": "drones are enabling new perspectives in photography and delivery services. #drones",
    "30": "solar energy technology is contributing to clean and sustainable power. #solar",
    "31": "fintech solutions are revolutionizing how we manage and interact with money. #fintech",
    "32": "augmented reality blends digital elements with the real world for immersive experiences. #ar",
    "33": "e-commerce platforms are shaping the future of retail and shopping. #ecommerce",
    "34": "voice assistants are simplifying tasks through voice commands and responses. #voice",
    "35": "3d printing technology is enabling rapid prototyping and custom manufacturing. #3dprinting",
    "36": "autonomous vehicles are driving the future of transportation with self-guiding tech. #autonomous",
    "37": "biometrics security uses unique human characteristics for authentication. #biometrics",
    "38": "containerization enables efficient and consistent software deployment. #containers",
    "39": "nanotechnology is enabling advancements in medicine, materials, and more. #nanotech",
    "40": "social media platforms connect people and ideas across the globe. #socialmedia",
    "41": "wireless charging technology is making charging devices more convenient. #wireless",
    "42": "graph databases are optimizing data relationships for improved insights. #graphdb",
    "43": "telemedicine technology is making healthcare more accessible and convenient. #telemedicine",
    "44": "smart homes are integrating technology for enhanced living experiences. #smarthomes",
    "45": "spatial computing is merging physical and digital realities for new experiences. #spatial",
    "46": "laptop technology keeps evolving for portable and powerful computing solutions. #laptops",
    "47": "agile methodologies enable adaptive and iterative software development processes. #agile",
    "48": "chatbots are enhancing customer service with automation and ai. #chatbots",
    "49": "5d storage technology might revolutionize data storage with durability. #5dstorage",
    "50": "serverless architectures allow developers to focus on code, not infrastructure. #serverless",
}
